### ISSUE TITLE
Fatal Crash: Game Does Not Progress Beyond Week 4 (v0.2.1-0222)

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#144]
Game crashes in Month 1, Week 4.

See attached logs and saved files

[Founder Life 0.2.1-0222-Crash001.txt](https://github.com/NellWatson/Founders-Life--New-Prototype/files/2923200/Founder.Life.0.2.1-0222-Crash001.txt)
[Founder Life 0.2.1-0222-Crash002.txt](https://github.com/NellWatson/Founders-Life--New-Prototype/files/2923201/Founder.Life.0.2.1-0222-Crash002.txt)
[saves.zip](https://github.com/NellWatson/Founders-Life--New-Prototype/files/2923202/saves.zip)

**Comment by DragoonHP** [comment]
So this is because of the issue I discussed on e-mail a few weeks back. Because of conditional events in Chapter 1, we can sometimes end up with no events in the event bucket on some particular (but random as it completely depends on events shown before) days after Week 2. (clicking on ignore should take you forward)

I can create a default event which will play when there are no events to play.

**Comment by kwangchow** [comment]
Thanks. Yes, can we insert the default event and label it in such a way that I can keep a count of how many times it appears in-play (on average). We can then create a bank of random events.

**Comment by DragoonHP** [comment]
Done!
